image: "alpine"
package_dir: /{{.Values.name}}
prelude:
- apk add zip curl
steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://github.com/whalebrew/whalebrew/releases/download/${PACKAGE_VERSION}/whalebrew-Linux-x86_64 -o /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
