image: "quay.io/mocaccino/extra"
prelude:
- luet install -y development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/lxd-compose.git
env:
- GIT_HASH=96ff3906eb57bc3676beb2483021f91fcb41459c
steps:
- cd lxd-compose && git checkout "${GIT_HASH}" && make build && mv lxd-compose /usr/bin/lxd-compose
includes:
- /usr/bin/lxd-compose
