image: "quay.io/mocaccino/extra"
prelude:
- luet install -y development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/lxd-compose.git
env:
- GIT_HASH=09a1bc78ef42bb19669a03f73ce746238afa1ece
steps:
- cd lxd-compose && git checkout "${GIT_HASH}" && make build && mv lxd-compose /usr/bin/lxd-compose
includes:
- /usr/bin/lxd-compose
