image: "quay.io/mocaccino/extra"
prelude:
- luet install -y development/make lang/go vcs/git
- git clone https://github.com/MottainaiCI/lxd-compose.git
env:
- GIT_HASH=80574289217688a718d532f997c0df8b992d640d
steps:
- cd lxd-compose && git checkout "${GIT_HASH}" && make build && mv lxd-compose /usr/bin/lxd-compose
includes:
- /usr/bin/lxd-compose
